dependencies:
  build:
  - maven:3.5.0
  - java:8.252.09
  - python:3.7.0

build_targets:
  - name: default
    container:
      image: yourbase/yb_ubuntu:18.04
    environment:
      - MAVEN_OPTS=-Xms2g -Xmx2g
    commands:
      - pip install -r intg/src/main/python/requirements.txt
      - pip install apache-atlas
      - mvn -B -Drat.numUnapprovedLicenses=100 package

ci:
  builds:
    - name: default
      build_target: default
